/*
 * Screenwriter API
 *
 * Data API for Screenwriter: an online collaborative screenwriting software.
 *
 * API version: 0.0.1
 * Contact: logan@theinitiativepg.ocm
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"DeleteDocument",
		strings.ToUpper("Delete"),
		"/v1/documents",
		DeleteDocument,
	},

	Route{
		"GetDocumentById",
		strings.ToUpper("Get"),
		"/v1/documents/{id}",
		GetDocumentById,
	},

	Route{
		"GetDocuments",
		strings.ToUpper("Get"),
		"/v1/documents",
		GetDocuments,
	},

	Route{
		"PostDocuments",
		strings.ToUpper("Post"),
		"/v1/documents",
		PostDocuments,
	},

	Route{
		"PutDocuments",
		strings.ToUpper("Put"),
		"/v1/documents",
		PutDocuments,
	},

	Route{
		"AddProject",
		strings.ToUpper("Post"),
		"/v1/projects",
		AddProject,
	},

	Route{
		"DeleteProject",
		strings.ToUpper("Delete"),
		"/v1/projects",
		DeleteProject,
	},

	Route{
		"GetProjectById",
		strings.ToUpper("Get"),
		"/v1/projects/{id}",
		GetProjectById,
	},

	Route{
		"GetProjectByName",
		strings.ToUpper("Get"),
		"/v1/projects/search?term=searchby&value=searchfor",
		GetProjectByName,
	},

	Route{
		"GetProjectDocuments",
		strings.ToUpper("Get"),
		"/v1/project/getProjectDocuments",
		GetProjectDocuments,
	},

	Route{
		"GetProjects",
		strings.ToUpper("Get"),
		"/v1/projects",
		GetProjects,
	},

	Route{
		"UpdateProject",
		strings.ToUpper("Put"),
		"/v1/projects",
		UpdateProject,
	},

	Route{
		"DeleteScripts",
		strings.ToUpper("Delete"),
		"/v1/scripts",
		DeleteScripts,
	},

	Route{
		"GetScriptById",
		strings.ToUpper("Get"),
		"/v1/scripts/{id}",
		GetScriptById,
	},

	Route{
		"GetScripts",
		strings.ToUpper("Get"),
		"/v1/scripts",
		GetScripts,
	},

	Route{
		"GetScriptsByTitle",
		strings.ToUpper("Get"),
		"/v1/scripts/search?term=searchby&value=searchfor",
		GetScriptsByTitle,
	},

	Route{
		"PostScripts",
		strings.ToUpper("Post"),
		"/v1/scripts",
		PostScripts,
	},

	Route{
		"PutScripts",
		strings.ToUpper("Put"),
		"/v1/scripts",
		PutScripts,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/v1/user",
		CreateUser,
	},

	Route{
		"CreateUsersWithArrayInput",
		strings.ToUpper("Post"),
		"/v1/user/createWithArray",
		CreateUsersWithArrayInput,
	},

	Route{
		"CreateUsersWithListInput",
		strings.ToUpper("Post"),
		"/v1/user/createWithList",
		CreateUsersWithListInput,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/v1/user/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/v1/user/{username}",
		GetUserByName,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/v1/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/v1/user/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/v1/user/{username}",
		UpdateUser,
	},
}
