---
swagger: "2.0"
info:
  description: "Data API for Screenwriter: an online collaborative screenwriting software."
  version: "0.0.1"
  title: "Screenwriter API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "logan@theinitiativepg.ocm"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "burningphantom.com"
basePath: "/v1"
tags:
- name: "projects"
  description: "The collected documents for a screenwriting project"
- name: "scripts"
  description: "Script document operations"
- name: "documents"
  description: "Text document operations"
- name: "user"
  description: "User settings operations"
schemes:
- "http"
paths:
  /projects:
    get:
      tags:
      - "projects"
      summary: "Get all projects"
      description: "Returns all projects for this account"
      operationId: "getProjects"
      security:
      - screenwriter_auth:
        - "read:projects"
    post:
      tags:
      - "projects"
      summary: "Add a new project to the account"
      description: ""
      operationId: "addProject"
      security:
      - screenwriter_auth:
        - "write:projects"
    put:
      tags:
      - "projects"
      summary: "Update an existing project"
      description: ""
      operationId: "updateProject"
      security:
      - screenwriter_auth:
        - "write:projects"
    delete:
      tags:
      - "projects"
      summary: "Delete an existing project"
      description: "Remove a project with all associated documents"
      operationId: "deleteProject"
      security:
      - screenwriter_auth:
        - "delete:projects"
  /projects/{id}:
    get:
      tags:
      - "projects"
      summary: "Find project by ID"
      description: "Returns a single project"
      operationId: "getProjectById"
      security:
      - screenwriter_auth:
        - "read:projects"
  /projects/search?term=searchby&value=searchfor:
    get:
      tags:
      - "projects"
      summary: "Finds Projects by name"
      description: "Each project should have a unique name"
      operationId: "getProjectByName"
      security:
      - screenwriter_auth:
        - "read:projects"
  /project/getProjectDocuments:
    get:
      tags:
      - "projects"
      summary: "Get project scripts"
      description: "Retrieve all scripts for a project"
      operationId: "getProjectDocuments"
  /scripts:
    get:
      tags:
      - "scripts"
      summary: "Get project scripts"
      description: "Retrieve all scripts for a project"
      operationId: "getScripts"
      security:
      - screenwriter_auth:
        - "read:scripts"
    post:
      tags:
      - "scripts"
      summary: "Add a new script"
      description: "Add a new script to a project"
      operationId: "postScripts"
      security:
      - screenwriter_auth:
        - "write:scripts"
    put:
      tags:
      - "scripts"
      summary: "Update a script"
      description: "Update an existing script in a project"
      operationId: "putScripts"
      security:
      - screenwriter_auth:
        - "write:scripts"
    delete:
      tags:
      - "scripts"
      summary: "Delete a script"
      description: "Delete a script from a project"
      operationId: "deleteScripts"
      security:
      - screenwriter_auth:
        - "delete:scripts"
  /scripts/{id}:
    get:
      tags:
      - "scripts"
      summary: "Find script by ID"
      description: "Returns a single script"
      operationId: "getScriptById"
      security:
      - screenwriter_auth:
        - "read:scripts"
  /scripts/search?term=searchby&value=searchfor:
    get:
      tags:
      - "scripts"
      summary: "Finds Scripts by title"
      description: "Each script should have a unique title"
      operationId: "getScriptsByTitle"
      security:
      - screenwriter_auth:
        - "read:scripts"
  /documents:
    get:
      tags:
      - "documents"
      summary: "Get documents scripts"
      description: "Retrieve all documents for a project"
      operationId: "getDocuments"
      security:
      - screenwriter_auth:
        - "read:documents"
    post:
      tags:
      - "documents"
      summary: "Add a new script"
      description: "Add a new document to a project"
      operationId: "postDocuments"
      security:
      - screenwriter_auth:
        - "write:documents"
    put:
      tags:
      - "documents"
      summary: "Update a document"
      description: "Update an existing document in a project"
      operationId: "putDocuments"
      security:
      - screenwriter_auth:
        - "write:documents"
    delete:
      tags:
      - "documents"
      summary: "Delete a document"
      description: "Delete a document from a project"
      operationId: "deleteDocument"
      security:
      - screenwriter_auth:
        - "delete:scripts"
  /documents/{id}:
    get:
      tags:
      - "documents"
      summary: "Find document by ID"
      description: "Returns a single document"
      operationId: "getDocumentById"
      security:
      - screenwriter_auth:
        - "read:documents"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
  /user/createWithArray:
    post:
      tags:
      - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithArrayInput"
  /user/createWithList:
    post:
      tags:
      - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithListInput"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
securityDefinitions:
  screenwriter_auth:
    type: "oauth2"
    authorizationUrl: "http://burningphantom.com/oauth/dialog"
    flow: "implicit"
    scopes:
      write:projects: "modify projects in your account"
      read:projects: "read your projects"
      delete:projects: "delete a project"
      write:scripts: "modify scripts in your projects"
      read:scripts: "read scripts in your projects"
      delete:scripts: "delete a script"
      write:documents: "modify documents in your projects"
      read:documents: "read documents in your projects"
      delete:documents: "delete a document"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"