/*
 * Screenwriter API
 *
 * Data API for Screenwriter: an online collaborative screenwriting software.
 *
 * API version: 0.0.1
 * Contact: logan@theinitiativepg.ocm
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"gopkg.in/mgo.v2/bson"
)

type Project struct {
	Id          bson.ObjectId `bson:"_id" json:"Id"`
	Title       string        `bson:"name" json:"title,omitempty"`
	Owner       bson.ObjectId `bson:"owner" json:"owner"`
	CreatedDate int64         `bson:"created_date" json:"created_date"`
	UpdatedDate int64         `bson:"updated_date,omitempty" json:"updated_date,omitempty"`
	Status      string        `bson:"status,omitempty" json:"status,omitempty"`
}
