/*
 * Screenwriter API
 *
 * Data API for Screenwriter: an online collaborative screenwriting software.
 *
 * API version: 0.0.1
 * Contact: logan@theinitiativepg.ocm
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"gopkg.in/mgo.v2/bson"
)

type Script struct {
	Id          bson.ObjectId `bson:"_id" json:"id,omitempty"`
	Title       string        `bson:"title" json:"title,omitempty"`
	Text        string        `bson:"text" json:"text,omitempty"`
	Author      bson.ObjectId `bson:"author" json:"author,omitempty"`
	CreatedDate int64         `bson:"created_date" json:"created_date,omitempty"`
	UpdatedDate int64         `bson:"updated_date" json:"updated_date,omitempty"`
	Status      string        `bson:"status" json:"status,omitempty"`
}
